import React from "react";
import { Composition } from "remotion";
import { PaperVideoComposition } from "./Composition";
import type { VideoScript } from "./types";

const defaultProps: VideoScript = {
  script_id: "deep-learning-explained",
  scenes: [
    // Scene 1: Title Card (2s)
    {
      title: "DEEP LEARNING",
      narration: "Welcome to the world of deep learning.",
      visual: "title_card",
      audio_path: null,
      duration_in_seconds: 2,
      sound_effect: "whoosh_impact",
      visuals: {
        svg_elements: [
          {
            type: "circle",
            data: "100",
            x: 540,
            y: 960,
            color: "#58C4DC",
            stroke_width: 6,
            animation: "scale",
            delay: 0,
          },
          {
            type: "circle",
            data: "150",
            x: 540,
            y: 960,
            color: "#FF6B6B",
            stroke_width: 4,
            animation: "scale",
            delay: 10,
          },
          {
            type: "circle",
            data: "200",
            x: 540,
            y: 960,
            color: "#4ECDC4",
            stroke_width: 3,
            animation: "scale",
            delay: 20,
          },
        ],
        background_color: "#0a0e27",
        particles: true,
        grid: true,
      },
    },

    // Scene 2: What is Deep Learning? (2s)
    {
      title: "Neural Networks",
      narration: "Deep learning uses artificial neural networks.",
      visual: "explainer",
      audio_path: null,
      duration_in_seconds: 2,
      sound_effect: "soft_ambient",
      visuals: {
        svg_elements: [
          // Input layer (3 neurons)
          {
            type: "circle",
            data: "35",
            x: 200,
            y: 700,
            color: "#58C4DC",
            stroke_width: 3,
            animation: "scale",
            delay: 0,
          },
          {
            type: "circle",
            data: "35",
            x: 200,
            y: 860,
            color: "#58C4DC",
            stroke_width: 3,
            animation: "scale",
            delay: 5,
          },
          {
            type: "circle",
            data: "35",
            x: 200,
            y: 1020,
            color: "#58C4DC",
            stroke_width: 3,
            animation: "scale",
            delay: 10,
          },

          // Hidden layer (4 neurons)
          {
            type: "circle",
            data: "35",
            x: 540,
            y: 640,
            color: "#FF6B6B",
            stroke_width: 3,
            animation: "scale",
            delay: 15,
          },
          {
            type: "circle",
            data: "35",
            x: 540,
            y: 800,
            color: "#FF6B6B",
            stroke_width: 3,
            animation: "scale",
            delay: 20,
          },
          {
            type: "circle",
            data: "35",
            x: 540,
            y: 960,
            color: "#FF6B6B",
            stroke_width: 3,
            animation: "scale",
            delay: 25,
          },
          {
            type: "circle",
            data: "35",
            x: 540,
            y: 1120,
            color: "#FF6B6B",
            stroke_width: 3,
            animation: "scale",
            delay: 30,
          },

          // Output layer (2 neurons)
          {
            type: "circle",
            data: "35",
            x: 880,
            y: 800,
            color: "#4ECDC4",
            stroke_width: 3,
            animation: "scale",
            delay: 35,
          },
          {
            type: "circle",
            data: "35",
            x: 880,
            y: 960,
            color: "#4ECDC4",
            stroke_width: 3,
            animation: "scale",
            delay: 40,
          },

          // Connections
          {
            type: "line",
            data: "540,640",
            x: 200,
            y: 700,
            color: "#58C4DC",
            stroke_width: 1.5,
            animation: "draw",
            delay: 45,
          },
          {
            type: "line",
            data: "540,800",
            x: 200,
            y: 860,
            color: "#58C4DC",
            stroke_width: 1.5,
            animation: "draw",
            delay: 48,
          },
          {
            type: "line",
            data: "880,800",
            x: 540,
            y: 640,
            color: "#FF6B6B",
            stroke_width: 1.5,
            animation: "draw",
            delay: 50,
          },

          {
            type: "text",
            data: "Input",
            x: 200,
            y: 600,
            color: "#FFFFFF",
            stroke_width: 0,
            animation: "fade",
            delay: 55,
          },
          {
            type: "text",
            data: "Hidden",
            x: 540,
            y: 540,
            color: "#FFFFFF",
            stroke_width: 0,
            animation: "fade",
            delay: 58,
          },
          {
            type: "text",
            data: "Output",
            x: 880,
            y: 700,
            color: "#FFFFFF",
            stroke_width: 0,
            animation: "fade",
            delay: 60,
          },
        ],
        background_color: "#0a0e27",
        particles: false,
        grid: true,
      },
    },

    // Scene 3: Layers (1.5s)
    {
      title: "Multiple Layers",
      narration: "Deep networks have many hidden layers.",
      visual: "key_point",
      audio_path: null,
      duration_in_seconds: 1.5,
      sound_effect: "pop",
      visuals: {
        svg_elements: [
          {
            type: "rect",
            data: "80,400",
            x: 200,
            y: 860,
            color: "#58C4DC",
            stroke_width: 4,
            animation: "scale",
            delay: 0,
          },
          {
            type: "rect",
            data: "80,400",
            x: 380,
            y: 860,
            color: "#FF6B6B",
            stroke_width: 4,
            animation: "scale",
            delay: 10,
          },
          {
            type: "rect",
            data: "80,400",
            x: 560,
            y: 860,
            color: "#4ECDC4",
            stroke_width: 4,
            animation: "scale",
            delay: 20,
          },
          {
            type: "rect",
            data: "80,400",
            x: 740,
            y: 860,
            color: "#FFE66D",
            stroke_width: 4,
            animation: "scale",
            delay: 30,
          },
          {
            type: "rect",
            data: "80,400",
            x: 920,
            y: 860,
            color: "#FF6B6B",
            stroke_width: 4,
            animation: "scale",
            delay: 40,
          },
          {
            type: "text",
            data: "Layer 1",
            x: 200,
            y: 700,
            color: "#FFF",
            stroke_width: 0,
            animation: "fade",
            delay: 50,
          },
          {
            type: "text",
            data: "Layer 2",
            x: 380,
            y: 700,
            color: "#FFF",
            stroke_width: 0,
            animation: "fade",
            delay: 52,
          },
          {
            type: "text",
            data: "Layer 3",
            x: 560,
            y: 700,
            color: "#FFF",
            stroke_width: 0,
            animation: "fade",
            delay: 54,
          },
        ],
        background_color: "#0a0e27",
        particles: false,
        grid: true,
      },
    },

    // Scene 4: Activation Functions (1.5s)
    {
      title: "Activation Functions",
      narration: "Neurons use activation functions.",
      visual: "explainer",
      audio_path: null,
      duration_in_seconds: 1.5,
      sound_effect: "whoosh",
      visuals: {
        svg_elements: [
          {
            type: "path",
            data: "M 100,960 Q 300,600 500,960 T 900,960",
            x: 0,
            y: 0,
            color: "#58C4DC",
            stroke_width: 5,
            animation: "draw",
            delay: 0,
          },
          {
            type: "equation",
            data: "σ(x) = 1/(1+e⁻ˣ)",
            x: 540,
            y: 1300,
            color: "#FFE66D",
            stroke_width: 0,
            animation: "fade",
            delay: 30,
          },
          {
            type: "text",
            data: "Sigmoid",
            x: 540,
            y: 600,
            color: "#FFF",
            stroke_width: 0,
            animation: "fade",
            delay: 40,
          },
        ],
        background_color: "#0a0e27",
        particles: false,
        grid: true,
      },
    },

    // Scene 5: Forward Propagation (1.5s)
    {
      title: "Forward Pass",
      narration: "Data flows forward through the network.",
      visual: "timeline",
      audio_path: null,
      duration_in_seconds: 1.5,
      sound_effect: "whoosh",
      visuals: {
        svg_elements: [
          {
            type: "circle",
            data: "50",
            x: 200,
            y: 860,
            color: "#58C4DC",
            stroke_width: 4,
            animation: "scale",
            delay: 0,
          },
          {
            type: "line",
            data: "540,860",
            x: 200,
            y: 860,
            color: "#58C4DC",
            stroke_width: 3,
            animation: "draw",
            delay: 15,
          },
          {
            type: "circle",
            data: "50",
            x: 540,
            y: 860,
            color: "#FF6B6B",
            stroke_width: 4,
            animation: "scale",
            delay: 30,
          },
          {
            type: "line",
            data: "880,860",
            x: 540,
            y: 860,
            color: "#FF6B6B",
            stroke_width: 3,
            animation: "draw",
            delay: 45,
          },
          {
            type: "circle",
            data: "50",
            x: 880,
            y: 860,
            color: "#4ECDC4",
            stroke_width: 4,
            animation: "scale",
            delay: 60,
          },
        ],
        background_color: "#0a0e27",
        particles: false,
        grid: true,
      },
    },

    // Scene 6: Backpropagation (2s)
    {
      title: "Backpropagation",
      narration: "Networks learn through backpropagation.",
      visual: "explainer",
      audio_path: null,
      duration_in_seconds: 2,
      sound_effect: "impact",
      visuals: {
        svg_elements: [
          {
            type: "circle",
            data: "50",
            x: 880,
            y: 860,
            color: "#FF6B6B",
            stroke_width: 4,
            animation: "pulse",
            delay: 0,
          },
          {
            type: "line",
            data: "540,860",
            x: 880,
            y: 860,
            color: "#FF6B6B",
            stroke_width: 3,
            animation: "draw",
            delay: 15,
          },
          {
            type: "circle",
            data: "50",
            x: 540,
            y: 860,
            color: "#FFE66D",
            stroke_width: 4,
            animation: "pulse",
            delay: 30,
          },
          {
            type: "line",
            data: "200,860",
            x: 540,
            y: 860,
            color: "#FFE66D",
            stroke_width: 3,
            animation: "draw",
            delay: 45,
          },
          {
            type: "circle",
            data: "50",
            x: 200,
            y: 860,
            color: "#4ECDC4",
            stroke_width: 4,
            animation: "pulse",
            delay: 60,
          },
          {
            type: "text",
            data: "Error ←",
            x: 540,
            y: 750,
            color: "#FF6B6B",
            stroke_width: 0,
            animation: "fade",
            delay: 40,
          },
        ],
        background_color: "#0a0e27",
        particles: false,
        grid: true,
      },
    },

    // Scene 7: Gradient Descent (1.5s)
    {
      title: "Gradient Descent",
      narration: "Optimizing weights using gradients.",
      visual: "explainer",
      audio_path: null,
      duration_in_seconds: 1.5,
      sound_effect: "soft_ambient",
      visuals: {
        svg_elements: [
          {
            type: "path",
            data: "M 150,600 Q 300,500 450,700 T 750,900 T 950,850",
            x: 0,
            y: 0,
            color: "#58C4DC",
            stroke_width: 4,
            animation: "draw",
            delay: 0,
          },
          {
            type: "circle",
            data: "20",
            x: 950,
            y: 850,
            color: "#FF6B6B",
            stroke_width: 3,
            animation: "pulse",
            delay: 40,
          },
          {
            type: "text",
            data: "Minimum",
            x: 950,
            y: 950,
            color: "#FFE66D",
            stroke_width: 0,
            animation: "fade",
            delay: 50,
          },
        ],
        background_color: "#0a0e27",
        particles: false,
        grid: true,
      },
    },

    // Scene 8: Loss Function (1.5s)
    {
      title: "Loss Function",
      narration: "Measuring prediction error.",
      visual: "statistic",
      audio_path: null,
      duration_in_seconds: 1.5,
      sound_effect: "whoosh",
      visuals: {
        svg_elements: [
          {
            type: "equation",
            data: "L = (y - ŷ)²",
            x: 540,
            y: 860,
            color: "#FF6B6B",
            stroke_width: 0,
            animation: "scale",
            delay: 0,
          },
          {
            type: "circle",
            data: "180",
            x: 540,
            y: 860,
            color: "#FF6B6B",
            stroke_width: 5,
            animation: "draw",
            delay: 20,
          },
        ],
        background_color: "#0a0e27",
        particles: false,
        grid: true,
      },
    },

    // Scene 9: CNNs (2s)
    {
      title: "Convolutional Networks",
      narration: "CNNs excel at image recognition.",
      visual: "explainer",
      audio_path: null,
      duration_in_seconds: 2,
      sound_effect: "impact",
      visuals: {
        svg_elements: [
          // 3x3 grid representing image
          {
            type: "rect",
            data: "80,80",
            x: 300,
            y: 700,
            color: "#58C4DC",
            stroke_width: 3,
            animation: "scale",
            delay: 0,
          },
          {
            type: "rect",
            data: "80,80",
            x: 400,
            y: 700,
            color: "#58C4DC",
            stroke_width: 3,
            animation: "scale",
            delay: 5,
          },
          {
            type: "rect",
            data: "80,80",
            x: 500,
            y: 700,
            color: "#58C4DC",
            stroke_width: 3,
            animation: "scale",
            delay: 10,
          },
          {
            type: "rect",
            data: "80,80",
            x: 300,
            y: 800,
            color: "#58C4DC",
            stroke_width: 3,
            animation: "scale",
            delay: 15,
          },
          {
            type: "rect",
            data: "80,80",
            x: 400,
            y: 800,
            color: "#FF6B6B",
            stroke_width: 3,
            animation: "scale",
            delay: 20,
          },
          {
            type: "rect",
            data: "80,80",
            x: 500,
            y: 800,
            color: "#58C4DC",
            stroke_width: 3,
            animation: "scale",
            delay: 25,
          },

          // Convolution filter
          {
            type: "rect",
            data: "120,120",
            x: 400,
            y: 750,
            color: "#FFE66D",
            stroke_width: 4,
            animation: "draw",
            delay: 35,
          },

          {
            type: "text",
            data: "Filter",
            x: 400,
            y: 650,
            color: "#FFE66D",
            stroke_width: 0,
            animation: "fade",
            delay: 45,
          },

          // Feature map
          {
            type: "rect",
            data: "100,100",
            x: 700,
            y: 860,
            color: "#4ECDC4",
            stroke_width: 4,
            animation: "scale",
            delay: 55,
          },
          {
            type: "text",
            data: "Feature",
            x: 700,
            y: 1000,
            color: "#FFF",
            stroke_width: 0,
            animation: "fade",
            delay: 60,
          },
        ],
        background_color: "#0a0e27",
        particles: false,
        grid: true,
      },
    },

    // Scene 10: RNNs (2s)
    {
      title: "Recurrent Networks",
      narration: "RNNs process sequential data.",
      visual: "explainer",
      audio_path: null,
      duration_in_seconds: 2,
      sound_effect: "whoosh",
      visuals: {
        svg_elements: [
          {
            type: "circle",
            data: "60",
            x: 300,
            y: 860,
            color: "#58C4DC",
            stroke_width: 4,
            animation: "scale",
            delay: 0,
          },
          {
            type: "circle",
            data: "60",
            x: 540,
            y: 860,
            color: "#FF6B6B",
            stroke_width: 4,
            animation: "scale",
            delay: 15,
          },
          {
            type: "circle",
            data: "60",
            x: 780,
            y: 860,
            color: "#4ECDC4",
            stroke_width: 4,
            animation: "scale",
            delay: 30,
          },

          // Forward connections
          {
            type: "line",
            data: "540,860",
            x: 300,
            y: 860,
            color: "#58C4DC",
            stroke_width: 3,
            animation: "draw",
            delay: 45,
          },
          {
            type: "line",
            data: "780,860",
            x: 540,
            y: 860,
            color: "#FF6B6B",
            stroke_width: 3,
            animation: "draw",
            delay: 50,
          },

          // Recurrent connection (loop)
          {
            type: "path",
            data: "M 540,800 Q 540,700 480,750 Q 540,700 600,750 Q 540,700 540,800",
            x: 0,
            y: 0,
            color: "#FFE66D",
            stroke_width: 3,
            animation: "draw",
            delay: 55,
          },

          {
            type: "text",
            data: "t-1",
            x: 300,
            y: 950,
            color: "#FFF",
            stroke_width: 0,
            animation: "fade",
            delay: 60,
          },
          {
            type: "text",
            data: "t",
            x: 540,
            y: 950,
            color: "#FFF",
            stroke_width: 0,
            animation: "fade",
            delay: 62,
          },
          {
            type: "text",
            data: "t+1",
            x: 780,
            y: 950,
            color: "#FFF",
            stroke_width: 0,
            animation: "fade",
            delay: 64,
          },
        ],
        background_color: "#0a0e27",
        particles: false,
        grid: true,
      },
    },

    // Scene 11: Training Data (1.5s)
    {
      title: "Training Data",
      narration: "Deep learning needs lots of data.",
      visual: "statistic",
      audio_path: null,
      duration_in_seconds: 1.5,
      sound_effect: "impact",
      visuals: {
        svg_elements: [
          {
            type: "equation",
            data: "1M+",
            x: 540,
            y: 860,
            color: "#58C4DC",
            stroke_width: 0,
            animation: "scale",
            delay: 0,
          },
          {
            type: "text",
            data: "Training Examples",
            x: 540,
            y: 1050,
            color: "#FFF",
            stroke_width: 0,
            animation: "fade",
            delay: 30,
          },
          {
            type: "circle",
            data: "200",
            x: 540,
            y: 860,
            color: "#58C4DC",
            stroke_width: 5,
            animation: "draw",
            delay: 20,
          },
        ],
        background_color: "#0a0e27",
        particles: true,
        grid: true,
      },
    },

    // Scene 12: GPU Power (1.5s)
    {
      title: "GPU Acceleration",
      narration: "GPUs make training faster.",
      visual: "explainer",
      audio_path: null,
      duration_in_seconds: 1.5,
      sound_effect: "whoosh",
      visuals: {
        svg_elements: [
          {
            type: "rect",
            data: "150,80",
            x: 300,
            y: 860,
            color: "#58C4DC",
            stroke_width: 4,
            animation: "scale",
            delay: 0,
          },
          {
            type: "rect",
            data: "150,80",
            x: 540,
            y: 860,
            color: "#FF6B6B",
            stroke_width: 4,
            animation: "scale",
            delay: 10,
          },
          {
            type: "rect",
            data: "150,80",
            x: 780,
            y: 860,
            color: "#4ECDC4",
            stroke_width: 4,
            animation: "scale",
            delay: 20,
          },
          {
            type: "text",
            data: "GPU Core",
            x: 540,
            y: 750,
            color: "#FFE66D",
            stroke_width: 0,
            animation: "fade",
            delay: 35,
          },
        ],
        background_color: "#0a0e27",
        particles: false,
        grid: true,
      },
    },

    // Scene 13: Batch Normalization (1.5s)
    {
      title: "Batch Normalization",
      narration: "Normalizing layer inputs.",
      visual: "explainer",
      audio_path: null,
      duration_in_seconds: 1.5,
      sound_effect: "soft_ambient",
      visuals: {
        svg_elements: [
          {
            type: "equation",
            data: "x̂ = (x-μ)/σ",
            x: 540,
            y: 860,
            color: "#4ECDC4",
            stroke_width: 0,
            animation: "fade",
            delay: 0,
          },
          {
            type: "circle",
            data: "180",
            x: 540,
            y: 860,
            color: "#4ECDC4",
            stroke_width: 4,
            animation: "draw",
            delay: 20,
          },
        ],
        background_color: "#0a0e27",
        particles: false,
        grid: true,
      },
    },

    // Scene 14: Dropout (1.5s)
    {
      title: "Dropout Regularization",
      narration: "Preventing overfitting.",
      visual: "explainer",
      audio_path: null,
      duration_in_seconds: 1.5,
      sound_effect: "pop",
      visuals: {
        svg_elements: [
          {
            type: "circle",
            data: "40",
            x: 200,
            y: 700,
            color: "#58C4DC",
            stroke_width: 3,
            animation: "scale",
            delay: 0,
          },
          {
            type: "circle",
            data: "40",
            x: 200,
            y: 860,
            color: "#666",
            stroke_width: 3,
            animation: "fade",
            delay: 5,
          },
          {
            type: "circle",
            data: "40",
            x: 200,
            y: 1020,
            color: "#58C4DC",
            stroke_width: 3,
            animation: "scale",
            delay: 10,
          },
          {
            type: "circle",
            data: "40",
            x: 540,
            y: 800,
            color: "#58C4DC",
            stroke_width: 3,
            animation: "scale",
            delay: 15,
          },
          {
            type: "circle",
            data: "40",
            x: 540,
            y: 960,
            color: "#666",
            stroke_width: 3,
            animation: "fade",
            delay: 20,
          },
          {
            type: "circle",
            data: "40",
            x: 880,
            y: 860,
            color: "#58C4DC",
            stroke_width: 3,
            animation: "scale",
            delay: 25,
          },
          {
            type: "text",
            data: "Dropped",
            x: 540,
            y: 700,
            color: "#FF6B6B",
            stroke_width: 0,
            animation: "fade",
            delay: 35,
          },
        ],
        background_color: "#0a0e27",
        particles: false,
        grid: true,
      },
    },

    // Scene 15: Transfer Learning (2s)
    {
      title: "Transfer Learning",
      narration: "Using pre-trained models.",
      visual: "explainer",
      audio_path: null,
      duration_in_seconds: 2,
      sound_effect: "whoosh",
      visuals: {
        svg_elements: [
          {
            type: "rect",
            data: "200,300",
            x: 300,
            y: 860,
            color: "#58C4DC",
            stroke_width: 4,
            animation: "scale",
            delay: 0,
          },
          {
            type: "text",
            data: "Pre-trained",
            x: 300,
            y: 730,
            color: "#FFF",
            stroke_width: 0,
            animation: "fade",
            delay: 20,
          },
          {
            type: "line",
            data: "700,860",
            x: 400,
            y: 860,
            color: "#FFE66D",
            stroke_width: 4,
            animation: "draw",
            delay: 35,
          },
          {
            type: "rect",
            data: "150,200",
            x: 780,
            y: 860,
            color: "#4ECDC4",
            stroke_width: 4,
            animation: "scale",
            delay: 50,
          },
          {
            type: "text",
            data: "Fine-tune",
            x: 780,
            y: 1050,
            color: "#FFF",
            stroke_width: 0,
            animation: "fade",
            delay: 60,
          },
        ],
        background_color: "#0a0e27",
        particles: false,
        grid: true,
      },
    },

    // Scene 16: Transformers (2s)
    {
      title: "Transformers",
      narration: "Attention mechanisms power modern AI.",
      visual: "explainer",
      audio_path: null,
      duration_in_seconds: 2,
      sound_effect: "impact",
      visuals: {
        svg_elements: [
          {
            type: "circle",
            data: "50",
            x: 540,
            y: 700,
            color: "#58C4DC",
            stroke_width: 4,
            animation: "scale",
            delay: 0,
          },
          {
            type: "circle",
            data: "50",
            x: 400,
            y: 900,
            color: "#FF6B6B",
            stroke_width: 4,
            animation: "scale",
            delay: 10,
          },
          {
            type: "circle",
            data: "50",
            x: 680,
            y: 900,
            color: "#4ECDC4",
            stroke_width: 4,
            animation: "scale",
            delay: 20,
          },
          {
            type: "circle",
            data: "50",
            x: 540,
            y: 1100,
            color: "#FFE66D",
            stroke_width: 4,
            animation: "scale",
            delay: 30,
          },

          // Attention connections
          {
            type: "line",
            data: "400,900",
            x: 540,
            y: 700,
            color: "#58C4DC",
            stroke_width: 2,
            animation: "draw",
            delay: 40,
          },
          {
            type: "line",
            data: "680,900",
            x: 540,
            y: 700,
            color: "#58C4DC",
            stroke_width: 2,
            animation: "draw",
            delay: 45,
          },
          {
            type: "line",
            data: "540,1100",
            x: 400,
            y: 900,
            color: "#FF6B6B",
            stroke_width: 2,
            animation: "draw",
            delay: 50,
          },
          {
            type: "line",
            data: "540,1100",
            x: 680,
            y: 900,
            color: "#4ECDC4",
            stroke_width: 2,
            animation: "draw",
            delay: 55,
          },

          {
            type: "text",
            data: "Attention",
            x: 540,
            y: 600,
            color: "#FFF",
            stroke_width: 0,
            animation: "fade",
            delay: 60,
          },
        ],
        background_color: "#0a0e27",
        particles: false,
        grid: true,
      },
    },

    // Scene 17: Image Classification (1.5s)
    {
      title: "Image Classification",
      narration: "Recognizing objects in images.",
      visual: "explainer",
      audio_path: null,
      duration_in_seconds: 1.5,
      sound_effect: "whoosh",
      visuals: {
        svg_elements: [
          {
            type: "rect",
            data: "180,180",
            x: 300,
            y: 860,
            color: "#58C4DC",
            stroke_width: 4,
            animation: "scale",
            delay: 0,
          },
          {
            type: "text",
            data: "Image",
            x: 300,
            y: 860,
            color: "#FFF",
            stroke_width: 0,
            animation: "fade",
            delay: 20,
          },
          {
            type: "line",
            data: "700,860",
            x: 390,
            y: 860,
            color: "#FFE66D",
            stroke_width: 4,
            animation: "draw",
            delay: 30,
          },
          {
            type: "text",
            data: "Cat: 95%",
            x: 780,
            y: 860,
            color: "#4ECDC4",
            stroke_width: 0,
            animation: "fade",
            delay: 50,
          },
        ],
        background_color: "#0a0e27",
        particles: false,
        grid: true,
      },
    },

    // Scene 18: Object Detection (1.5s)
    {
      title: "Object Detection",
      narration: "Finding objects in scenes.",
      visual: "explainer",
      audio_path: null,
      duration_in_seconds: 1.5,
      sound_effect: "pop",
      visuals: {
        svg_elements: [
          {
            type: "rect",
            data: "250,200",
            x: 540,
            y: 860,
            color: "#58C4DC",
            stroke_width: 4,
            animation: "scale",
            delay: 0,
          },
          {
            type: "rect",
            data: "100,100",
            x: 400,
            y: 800,
            color: "#FF6B6B",
            stroke_width: 3,
            animation: "draw",
            delay: 20,
          },
          {
            type: "rect",
            data: "80,80",
            x: 650,
            y: 900,
            color: "#4ECDC4",
            stroke_width: 3,
            animation: "draw",
            delay: 30,
          },
          {
            type: "text",
            data: "Person",
            x: 400,
            y: 720,
            color: "#FF6B6B",
            stroke_width: 0,
            animation: "fade",
            delay: 45,
          },
          {
            type: "text",
            data: "Car",
            x: 650,
            y: 1020,
            color: "#4ECDC4",
            stroke_width: 0,
            animation: "fade",
            delay: 50,
          },
        ],
        background_color: "#0a0e27",
        particles: false,
        grid: true,
      },
    },

    // Scene 19: NLP Applications (2s)
    {
      title: "Natural Language",
      narration: "Understanding human language.",
      visual: "explainer",
      audio_path: null,
      duration_in_seconds: 2,
      sound_effect: "soft_ambient",
      visuals: {
        svg_elements: [
          {
            type: "text",
            data: "Hello",
            x: 200,
            y: 800,
            color: "#58C4DC",
            stroke_width: 0,
            animation: "fade",
            delay: 0,
          },
          {
            type: "text",
            data: "World",
            x: 450,
            y: 800,
            color: "#FF6B6B",
            stroke_width: 0,
            animation: "fade",
            delay: 15,
          },
          {
            type: "text",
            data: "!",
            x: 700,
            y: 800,
            color: "#4ECDC4",
            stroke_width: 0,
            animation: "fade",
            delay: 30,
          },
          {
            type: "line",
            data: "450,920",
            x: 200,
            y: 920,
            color: "#FFE66D",
            stroke_width: 3,
            animation: "draw",
            delay: 45,
          },
          {
            type: "line",
            data: "700,920",
            x: 450,
            y: 920,
            color: "#FFE66D",
            stroke_width: 3,
            animation: "draw",
            delay: 50,
          },
          {
            type: "text",
            data: "Embedding",
            x: 540,
            y: 1050,
            color: "#FFF",
            stroke_width: 0,
            animation: "fade",
            delay: 60,
          },
        ],
        background_color: "#0a0e27",
        particles: false,
        grid: true,
      },
    },

    // Scene 20: Generative Models (2s)
    {
      title: "Generative AI",
      narration: "Creating new content.",
      visual: "explainer",
      audio_path: null,
      duration_in_seconds: 2,
      sound_effect: "impact",
      visuals: {
        svg_elements: [
          {
            type: "circle",
            data: "60",
            x: 300,
            y: 860,
            color: "#58C4DC",
            stroke_width: 4,
            animation: "scale",
            delay: 0,
          },
          {
            type: "text",
            data: "Noise",
            x: 300,
            y: 750,
            color: "#FFF",
            stroke_width: 0,
            animation: "fade",
            delay: 15,
          },
          {
            type: "line",
            data: "780,860",
            x: 360,
            y: 860,
            color: "#FFE66D",
            stroke_width: 4,
            animation: "draw",
            delay: 30,
          },
          {
            type: "rect",
            data: "150,150",
            x: 780,
            y: 860,
            color: "#4ECDC4",
            stroke_width: 4,
            animation: "scale",
            delay: 50,
          },
          {
            type: "text",
            data: "Image",
            x: 780,
            y: 1020,
            color: "#FFF",
            stroke_width: 0,
            animation: "fade",
            delay: 60,
          },
        ],
        background_color: "#0a0e27",
        particles: true,
        grid: true,
      },
    },

    // Scene 21: GANs (2s)
    {
      title: "GANs",
      narration: "Generator versus discriminator.",
      visual: "comparison",
      audio_path: null,
      duration_in_seconds: 2,
      sound_effect: "whoosh",
      visuals: {
        svg_elements: [
          {
            type: "rect",
            data: "150,200",
            x: 300,
            y: 860,
            color: "#58C4DC",
            stroke_width: 4,
            animation: "scale",
            delay: 0,
          },
          {
            type: "text",
            data: "Generator",
            x: 300,
            y: 1050,
            color: "#FFF",
            stroke_width: 0,
            animation: "fade",
            delay: 20,
          },
          {
            type: "rect",
            data: "150,200",
            x: 780,
            y: 860,
            color: "#FF6B6B",
            stroke_width: 4,
            animation: "scale",
            delay: 30,
          },
          {
            type: "text",
            data: "Discriminator",
            x: 780,
            y: 1050,
            color: "#FFF",
            stroke_width: 0,
            animation: "fade",
            delay: 50,
          },
          {
            type: "line",
            data: "710,860",
            x: 375,
            y: 860,
            color: "#FFE66D",
            stroke_width: 3,
            animation: "draw",
            delay: 60,
          },
        ],
        background_color: "#0a0e27",
        particles: false,
        grid: true,
      },
    },

    // Scene 22: Reinforcement Learning (2s)
    {
      title: "Reinforcement Learning",
      narration: "Learning through rewards.",
      visual: "timeline",
      audio_path: null,
      duration_in_seconds: 2,
      sound_effect: "impact",
      visuals: {
        svg_elements: [
          {
            type: "circle",
            data: "60",
            x: 300,
            y: 860,
            color: "#58C4DC",
            stroke_width: 4,
            animation: "scale",
            delay: 0,
          },
          {
            type: "text",
            data: "Agent",
            x: 300,
            y: 750,
            color: "#FFF",
            stroke_width: 0,
            animation: "fade",
            delay: 15,
          },
          {
            type: "line",
            data: "600,860",
            x: 360,
            y: 860,
            color: "#FFE66D",
            stroke_width: 3,
            animation: "draw",
            delay: 25,
          },
          {
            type: "circle",
            data: "60",
            x: 780,
            y: 860,
            color: "#FF6B6B",
            stroke_width: 4,
            animation: "scale",
            delay: 40,
          },
          {
            type: "text",
            data: "Environment",
            x: 780,
            y: 750,
            color: "#FFF",
            stroke_width: 0,
            animation: "fade",
            delay: 55,
          },
          {
            type: "path",
            data: "M 780,920 Q 540,1100 300,920",
            x: 0,
            y: 0,
            color: "#4ECDC4",
            stroke_width: 3,
            animation: "draw",
            delay: 60,
          },
          {
            type: "text",
            data: "Reward",
            x: 540,
            y: 1150,
            color: "#4ECDC4",
            stroke_width: 0,
            animation: "fade",
            delay: 70,
          },
        ],
        background_color: "#0a0e27",
        particles: false,
        grid: true,
      },
    },

    // Scene 23: Real-World Apps (2s)
    {
      title: "Applications",
      narration: "Transforming industries everywhere.",
      visual: "key_point",
      audio_path: null,
      duration_in_seconds: 2,
      sound_effect: "whoosh",
      visuals: {
        svg_elements: [
          {
            type: "circle",
            data: "80",
            x: 270,
            y: 700,
            color: "#58C4DC",
            stroke_width: 4,
            animation: "scale",
            delay: 0,
          },
          {
            type: "text",
            data: "Healthcare",
            x: 270,
            y: 710,
            color: "#FFF",
            stroke_width: 0,
            animation: "fade",
            delay: 15,
          },

          {
            type: "circle",
            data: "80",
            x: 810,
            y: 700,
            color: "#FF6B6B",
            stroke_width: 4,
            animation: "scale",
            delay: 20,
          },
          {
            type: "text",
            data: "Finance",
            x: 810,
            y: 710,
            color: "#FFF",
            stroke_width: 0,
            animation: "fade",
            delay: 35,
          },

          {
            type: "circle",
            data: "80",
            x: 270,
            y: 1020,
            color: "#4ECDC4",
            stroke_width: 4,
            animation: "scale",
            delay: 40,
          },
          {
            type: "text",
            data: "Automotive",
            x: 270,
            y: 1030,
            color: "#FFF",
            stroke_width: 0,
            animation: "fade",
            delay: 55,
          },

          {
            type: "circle",
            data: "80",
            x: 810,
            y: 1020,
            color: "#FFE66D",
            stroke_width: 4,
            animation: "scale",
            delay: 60,
          },
          {
            type: "text",
            data: "Education",
            x: 810,
            y: 1030,
            color: "#FFF",
            stroke_width: 0,
            animation: "fade",
            delay: 75,
          },
        ],
        background_color: "#0a0e27",
        particles: false,
        grid: true,
      },
    },

    // Scene 24: Future of AI (2s)
    {
      title: "The Future",
      narration: "Deep learning continues to evolve.",
      visual: "conclusion",
      audio_path: null,
      duration_in_seconds: 2,
      sound_effect: "impact",
      visuals: {
        svg_elements: [
          {
            type: "circle",
            data: "100",
            x: 540,
            y: 860,
            color: "#58C4DC",
            stroke_width: 5,
            animation: "scale",
            delay: 0,
          },
          {
            type: "circle",
            data: "150",
            x: 540,
            y: 860,
            color: "#FF6B6B",
            stroke_width: 4,
            animation: "scale",
            delay: 15,
          },
          {
            type: "circle",
            data: "200",
            x: 540,
            y: 860,
            color: "#4ECDC4",
            stroke_width: 3,
            animation: "scale",
            delay: 30,
          },
          {
            type: "text",
            data: "AI",
            x: 540,
            y: 870,
            color: "#FFF",
            stroke_width: 0,
            animation: "fade",
            delay: 45,
          },
        ],
        background_color: "#0a0e27",
        particles: true,
        grid: true,
      },
    },

    // Scene 25: Conclusion (2s)
    {
      title: "DEEP LEARNING",
      narration: "Thank you for watching!",
      visual: "conclusion",
      audio_path: null,
      duration_in_seconds: 2,
      sound_effect: "whoosh_impact",
      visuals: {
        svg_elements: [
          {
            type: "circle",
            data: "250",
            x: 540,
            y: 960,
            color: "#58C4DC",
            stroke_width: 6,
            animation: "draw",
            delay: 0,
          },
          {
            type: "text",
            data: "Thank You",
            x: 540,
            y: 1300,
            color: "#FFE66D",
            stroke_width: 0,
            animation: "fade",
            delay: 40,
          },
        ],
        background_color: "#0a0e27",
        particles: true,
        grid: true,
      },
    },
  ],
  total_duration_seconds: 43,
};

export const RemotionRoot: React.FC = () => {
  return (
    <>
      <Composition
        id="PaperVideo"
        component={PaperVideoComposition as any}
        width={1080}
        height={1920}
        fps={30}
        durationInFrames={1290} // 43 seconds * 30fps
        defaultProps={defaultProps}
      />
    </>
  );
};
