
import React from "react";
import { Composition } from "remotion";
import { PaperVideoComposition } from "./Composition";
import type { VideoScript } from "./types";

// This file is auto-generated by the update_remotion.py script.
// Do not edit this file directly.
// Source JSON: 2511.08525v1.json

const defaultProps: VideoScript = {
  "script_id": "2511.08525v1",
  "scenes": [
    {
      "title": "CoT Monitorability: Introduction",
      "narration": "Large Reasoning Models excel at complex tasks by thinking step-by-step, offering a chance to monitor their internal chain-of-thought.",
      "visual": "A vertical flow diagram illustrating the relationship between Reasoning Models and their Chain-of-Thought for safety monitoring.",
      "audio_path": "audio/2511.08525v1_scene_0.mp3",
      "duration_in_seconds": 9.144,
      "sound_effect": "soft_swoosh",
      "visuals": {
        "svg_elements": [
          {
            "type": "text",
            "data": "CoT Monitorability",
            "x": 540.0,
            "y": 300.0,
            "color": "#F4B844",
            "stroke_width": 0.0,
            "animation": "fade",
            "delay": 0.0
          },
          {
            "type": "lucide_icon",
            "data": "Cpu,80",
            "x": 540.0,
            "y": 680.0,
            "color": "#6B9BD1",
            "stroke_width": 3.0,
            "animation": "draw",
            "delay": 20.0
          },
          {
            "type": "text",
            "data": "Reasoning Models",
            "x": 540.0,
            "y": 800.0,
            "color": "#6B9BD1",
            "stroke_width": 0.0,
            "animation": "fade",
            "delay": 40.0
          },
          {
            "type": "path",
            "data": "M 540 760 L 540 890 M 520 870 L 540 890 L 560 870",
            "x": 0.0,
            "y": 0.0,
            "color": "#90A4AE",
            "stroke_width": 2.0,
            "animation": "draw",
            "delay": 50.0
          },
          {
            "type": "lucide_icon",
            "data": "Brain,80",
            "x": 540.0,
            "y": 980.0,
            "color": "#A8D8B9",
            "stroke_width": 3.0,
            "animation": "draw",
            "delay": 70.0
          }
        ],
        "background_color": "#0a0e27",
        "particles": false,
        "grid": false
      },
      "transcription": [
        {
          "text": "Large reasoning models excel at complex tasks by thinking step-by-step, offering a chance to monitor their internal chain of thought.",
          "start": 0.0,
          "end": 9.0
        }
      ]
    },
    {
      "title": "Unfaithful Explanations",
      "narration": "Models may not truthfully verbalize their true factors, often generating plausible justifications rather than real decision factors.",
      "visual": "An LRM's true internal thought is concealed by an outwardly presented, unfaithful explanation, symbolized by a mask.",
      "audio_path": "audio/2511.08525v1_scene_1.mp3",
      "duration_in_seconds": 9.696,
      "sound_effect": "quick_whoosh",
      "visuals": {
        "svg_elements": [
          {
            "type": "text",
            "data": "Unfaithful Explanations",
            "x": 540.0,
            "y": 300.0,
            "color": "#E57373",
            "stroke_width": 0.0,
            "animation": "fade",
            "delay": 0.0
          },
          {
            "type": "lucide_icon",
            "data": "Cpu,90",
            "x": 540.0,
            "y": 750.0,
            "color": "#A8D8B9",
            "stroke_width": 3.0,
            "animation": "draw",
            "delay": 20.0
          },
          {
            "type": "circle",
            "data": "50",
            "x": 540.0,
            "y": 950.0,
            "color": "#4DB6AC",
            "stroke_width": 4.0,
            "animation": "scale",
            "delay": 40.0
          },
          {
            "type": "text",
            "data": "True Decision Factor",
            "x": 540.0,
            "y": 1050.0,
            "color": "#4DB6AC",
            "stroke_width": 0.0,
            "animation": "fade",
            "delay": 60.0
          },
          {
            "type": "lucide_icon",
            "data": "EyeOff,80",
            "x": 540.0,
            "y": 1380.0,
            "color": "#E57373",
            "stroke_width": 3.0,
            "animation": "draw",
            "delay": 80.0
          }
        ],
        "background_color": "#0a0e27",
        "particles": false,
        "grid": false
      },
      "transcription": [
        {
          "text": "Models may not truthfully verbalize their true factors, often generating plausible justifications",
          "start": 0.0,
          "end": 6.6000000000000005
        },
        {
          "text": "rather than real decision factors.",
          "start": 6.6000000000000005,
          "end": 8.88
        }
      ]
    },
    {
      "title": "Monitor Reliability",
      "narration": "Monitors may be overly sensitive, flagging benign behavior, or insufficiently sensitive, missing crucial misbehavior, posing a key challenge.",
      "visual": "A central target icon representing a monitor, flanked by concepts of oversensitivity (false positives) and undersensitivity (false negatives).",
      "audio_path": "audio/2511.08525v1_scene_2.mp3",
      "duration_in_seconds": 10.728,
      "sound_effect": "data_stream",
      "visuals": {
        "svg_elements": [
          {
            "type": "text",
            "data": "Monitor Reliability",
            "x": 540.0,
            "y": 300.0,
            "color": "#A8D8B9",
            "stroke_width": 0.0,
            "animation": "fade",
            "delay": 0.0
          },
          {
            "type": "lucide_icon",
            "data": "Target,90",
            "x": 540.0,
            "y": 750.0,
            "color": "#F4B844",
            "stroke_width": 3.0,
            "animation": "draw",
            "delay": 20.0
          },
          {
            "type": "rect",
            "data": "250,100",
            "x": 300.0,
            "y": 1050.0,
            "color": "#E57373",
            "stroke_width": 4.0,
            "animation": "scale",
            "delay": 40.0
          },
          {
            "type": "text",
            "data": "False Positives",
            "x": 300.0,
            "y": 1050.0,
            "color": "#FFFFFF",
            "stroke_width": 0.0,
            "animation": "fade",
            "delay": 60.0
          },
          {
            "type": "rect",
            "data": "250,100",
            "x": 780.0,
            "y": 1350.0,
            "color": "#F4B844",
            "stroke_width": 4.0,
            "animation": "scale",
            "delay": 80.0
          }
        ],
        "background_color": "#0a0e27",
        "particles": false,
        "grid": false
      },
      "transcription": [
        {
          "text": "monitors may be overly sensitive, flagging benign behavior, or insufficiently sensitive,",
          "start": 0.0,
          "end": 6.16
        },
        {
          "text": "missing crucial misbehavior, posing a key challenge.",
          "start": 6.16,
          "end": 10.64
        }
      ]
    },
    {
      "title": "Verbalization Metrics",
      "narration": "We measure verbalization quality through robustness: resisting cues while verbalizing them, and scheming: being influenced yet concealing it.",
      "visual": "Two distinct rectangles representing 'Robustness' and 'Scheming' metrics with their descriptive text.",
      "audio_path": "audio/2511.08525v1_scene_3.mp3",
      "duration_in_seconds": 10.032,
      "sound_effect": "completion_bell",
      "visuals": {
        "svg_elements": [
          {
            "type": "text",
            "data": "Verbalization Metrics",
            "x": 540.0,
            "y": 300.0,
            "color": "#A8D8B9",
            "stroke_width": 0.0,
            "animation": "fade",
            "delay": 0.0
          },
          {
            "type": "rect",
            "data": "280,120",
            "x": 300.0,
            "y": 900.0,
            "color": "#BA68C8",
            "stroke_width": 4.0,
            "animation": "scale",
            "delay": 20.0
          },
          {
            "type": "text",
            "data": "Robustness",
            "x": 300.0,
            "y": 900.0,
            "color": "#FFFFFF",
            "stroke_width": 0.0,
            "animation": "fade",
            "delay": 40.0
          },
          {
            "type": "rect",
            "data": "280,120",
            "x": 780.0,
            "y": 1350.0,
            "color": "#E57373",
            "stroke_width": 4.0,
            "animation": "scale",
            "delay": 60.0
          },
          {
            "type": "text",
            "data": "Scheming",
            "x": 780.0,
            "y": 1350.0,
            "color": "#FFFFFF",
            "stroke_width": 0.0,
            "animation": "fade",
            "delay": 80.0
          }
        ],
        "background_color": "#0a0e27",
        "particles": false,
        "grid": false
      },
      "transcription": [
        {
          "text": "We measure verbalization quality through robustness,",
          "start": 0.0,
          "end": 3.6
        },
        {
          "text": "resisting cues while verbalizing them, and scheming,",
          "start": 3.6,
          "end": 7.12
        },
        {
          "text": "being influenced yet concealing it.",
          "start": 7.12,
          "end": 9.92
        }
      ]
    },
    {
      "title": "Monitor Reliability Metrics",
      "narration": "To assess monitor effectiveness, we use EEMR: undetected misbehavior, and OSM: false alarms when models perform correctly.",
      "visual": "A central concept of Monitor Effectiveness connected to EEMR and OSM metrics via an arrow, emphasizing their relation.",
      "audio_path": "audio/2511.08525v1_scene_4.mp3",
      "duration_in_seconds": 10.776,
      "sound_effect": "digital_pulse",
      "visuals": {
        "svg_elements": [
          {
            "type": "text",
            "data": "Monitor Metrics",
            "x": 540.0,
            "y": 300.0,
            "color": "#F4B844",
            "stroke_width": 0.0,
            "animation": "fade",
            "delay": 0.0
          },
          {
            "type": "circle",
            "data": "60",
            "x": 540.0,
            "y": 800.0,
            "color": "#AB47BC",
            "stroke_width": 4.0,
            "animation": "scale",
            "delay": 20.0
          },
          {
            "type": "text",
            "data": "Monitor Effectiveness",
            "x": 540.0,
            "y": 950.0,
            "color": "#AB47BC",
            "stroke_width": 0.0,
            "animation": "fade",
            "delay": 40.0
          },
          {
            "type": "path",
            "data": "M 400 1100 L 250 1250 M 230 1230 L 250 1250 L 270 1230",
            "x": 0.0,
            "y": 0.0,
            "color": "#90A4AE",
            "stroke_width": 2.0,
            "animation": "draw",
            "delay": 60.0
          },
          {
            "type": "text",
            "data": "EEMR: Undetected Misbehavior",
            "x": 250.0,
            "y": 1400.0,
            "color": "#4DB6AC",
            "stroke_width": 0.0,
            "animation": "fade",
            "delay": 80.0
          }
        ],
        "background_color": "#0a0e27",
        "particles": false,
        "grid": false
      },
      "transcription": [
        {
          "text": "To assess monitor effectiveness, we use EEMR, undetected misbehavior, and OSM.",
          "start": 0.0,
          "end": 7.2
        },
        {
          "text": "False alarms when models perform correctly.",
          "start": 7.2,
          "end": 10.72
        }
      ]
    },
    {
      "title": "CoT Interventions Impact",
      "narration": "Different reasoning interventions also affect monitorability; longer, self-explaining thoughts can improve robustness and reduce deceptive behavior.",
      "visual": "A brain icon demonstrating two reasoning paths: short and long, with their respective impacts on monitorability.",
      "audio_path": "audio/2511.08525v1_scene_5.mp3",
      "duration_in_seconds": 11.016,
      "sound_effect": "spark_zap",
      "visuals": {
        "svg_elements": [
          {
            "type": "text",
            "data": "CoT Interventions Impact",
            "x": 540.0,
            "y": 300.0,
            "color": "#A8D8B9",
            "stroke_width": 0.0,
            "animation": "fade",
            "delay": 0.0
          },
          {
            "type": "lucide_icon",
            "data": "Brain,90",
            "x": 540.0,
            "y": 750.0,
            "color": "#81C784",
            "stroke_width": 3.0,
            "animation": "draw",
            "delay": 20.0
          },
          {
            "type": "line",
            "data": "650,1050",
            "x": 430.0,
            "y": 950.0,
            "color": "#F4B844",
            "stroke_width": 4.0,
            "animation": "draw",
            "delay": 40.0
          },
          {
            "type": "text",
            "data": "Longer Path: More Transparent",
            "x": 540.0,
            "y": 1150.0,
            "color": "#F4B844",
            "stroke_width": 0.0,
            "animation": "fade",
            "delay": 60.0
          },
          {
            "type": "line",
            "data": "600,1350",
            "x": 480.0,
            "y": 1250.0,
            "color": "#81C784",
            "stroke_width": 4.0,
            "animation": "draw",
            "delay": 80.0
          }
        ],
        "background_color": "#0a0e27",
        "particles": false,
        "grid": false
      },
      "transcription": [
        {
          "text": "Different reasoning interventions also affect monetarability.",
          "start": 0.0,
          "end": 4.4
        },
        {
          "text": "Longer, self-explaning thoughts can improve robustness and reduce deceptive behavior.",
          "start": 4.4,
          "end": 10.64
        }
      ]
    },
    {
      "title": "Introducing MoME",
      "narration": "To address monitoring limitations, we propose MoME, a new paradigm that guides monitors to produce structured, evidence-based judgments.",
      "visual": "A central MoME label with a magnifying glass, emphasizing its role in generating structured, evidence-based judgments.",
      "audio_path": "audio/2511.08525v1_scene_6.mp3",
      "duration_in_seconds": 9.888,
      "sound_effect": "slide_in",
      "visuals": {
        "svg_elements": [
          {
            "type": "text",
            "data": "Introducing MoME",
            "x": 540.0,
            "y": 300.0,
            "color": "#6B9BD1",
            "stroke_width": 0.0,
            "animation": "fade",
            "delay": 0.0
          },
          {
            "type": "rect",
            "data": "250,100",
            "x": 540.0,
            "y": 800.0,
            "color": "#81C784",
            "stroke_width": 4.0,
            "animation": "scale",
            "delay": 20.0
          },
          {
            "type": "text",
            "data": "MoME",
            "x": 540.0,
            "y": 800.0,
            "color": "#FFFFFF",
            "stroke_width": 0.0,
            "animation": "fade",
            "delay": 40.0
          },
          {
            "type": "lucide_icon",
            "data": "Search,70",
            "x": 540.0,
            "y": 1100.0,
            "color": "#FFA726",
            "stroke_width": 3.0,
            "animation": "draw",
            "delay": 60.0
          },
          {
            "type": "text",
            "data": "Evidence-Based Judgments",
            "x": 540.0,
            "y": 1250.0,
            "color": "#FFA726",
            "stroke_width": 0.0,
            "animation": "fade",
            "delay": 80.0
          }
        ],
        "background_color": "#0a0e27",
        "particles": false,
        "grid": false
      },
      "transcription": [
        {
          "text": "To address monitoring limitations, we propose MOM, a new paradigm that guides monitors to produce structured, evidence-based judgments.",
          "start": 0.0,
          "end": 9.6
        }
      ]
    },
    {
      "title": "MoME's Enhanced Effectiveness",
      "narration": "MoME improves monitoring effectiveness by balancing false positives and negatives, offering more nuanced and reliable misbehavior assessments.",
      "visual": "A mathematical equation representing Monitor Effectiveness Score (MES), highlighting MoME's balanced approach to misbehavior assessment.",
      "audio_path": "audio/2511.08525v1_scene_7.mp3",
      "duration_in_seconds": 10.176,
      "sound_effect": "success_chime",
      "visuals": {
        "svg_elements": [
          {
            "type": "text",
            "data": "MoME: Superior Effectiveness",
            "x": 540.0,
            "y": 300.0,
            "color": "#F4B844",
            "stroke_width": 0.0,
            "animation": "fade",
            "delay": 0.0
          },
          {
            "type": "equation",
            "data": "MES = (1 - EEMR) \u22c5 (1 - OSM)",
            "x": 540.0,
            "y": 800.0,
            "color": "#42A5F5",
            "stroke_width": 0.0,
            "animation": "fade",
            "delay": 20.0
          },
          {
            "type": "rect",
            "data": "250,100",
            "x": 300.0,
            "y": 1200.0,
            "color": "#66BB6A",
            "stroke_width": 4.0,
            "animation": "scale",
            "delay": 40.0
          },
          {
            "type": "text",
            "data": "Balanced Monitoring",
            "x": 300.0,
            "y": 1300.0,
            "color": "#66BB6A",
            "stroke_width": 0.0,
            "animation": "fade",
            "delay": 60.0
          },
          {
            "type": "lucide_icon",
            "data": "BadgeCheck,70",
            "x": 780.0,
            "y": 1450.0,
            "color": "#42A5F5",
            "stroke_width": 3.0,
            "animation": "draw",
            "delay": 80.0
          }
        ],
        "background_color": "#0a0e27",
        "particles": false,
        "grid": false
      },
      "transcription": [
        {
          "text": "MoM improves monitoring effectiveness by balancing false positives and negatives, offering more nuanced and reliable misbehavior assessments.",
          "start": 0.0,
          "end": 10.0
        }
      ]
    }
  ],
  "total_duration_seconds": 81.45599999999999
};

export const RemotionRoot: React.FC = () => {
  return (
    <>
      <Composition
        id="PaperVideo"
        component={PaperVideoComposition as any}
        width={1080}
        height={1920}
        fps={30}
        durationInFrames={2443} // 81.45599999999999 seconds * 30fps
        defaultProps={defaultProps}
      />
    </>
  );
};
