@echo OFF
echo Starting Backend Server...

echo Activating Python virtual environment...
CALL .\.venv\Scripts\activate.bat

echo Navigating to backend directory...
cd backend

echo Starting Uvicorn server at http://0.0.0.0:8000...
uvicorn app.main:app --host 0.0.0.0 --port 8000